apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
#---
#apiVersion: keda.sh/v1alpha1
#kind: ScaledObject
#metadata:
#  name: nginx-scaledobject
#spec:
#  scaleTargetRef:
#    name: test-deployment
#  triggers:
#    - type: cpu
#      metadata:
#        type: Utilization
#        value: "50"
